### ISSUE TITLE
no, it doesn't work

### ISSUE THREAD

**Issue by crixthegreat** [Sean16SYSU/ipv6-dns#1]
Do I need something else except for the file-copy?

**Comment by Sean16SYSU** [comment]
Theoretically speaking, **No** .

**Check:** If you replace the file in `etc` and your computer owns IPv6 address, then everything is ready.

**What "may" help:** If 'Google' is still unaccessible after you have done what I mention before, you can try to use  `tracert bt.byr.cn`  in command.
